name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # 3. Instalar dependencias
    - name: Install dependencies
      run: poetry install

    # 4. Ejecutar pruebas (pueden fallar)
    - name: Run tests
      run: poetry run pytest --cov=app --cov-report=xml
      continue-on-error: true

    # 5. Subir cobertura a Codecov
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)